name: Self-Hosted Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python 3.11.3
        run: |
          # Download Python installer
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.11.3/python-3.11.3-amd64.exe -OutFile python-installer.exe
          # Install Python
          Start-Process -Wait -FilePath python-installer.exe -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1 Include_launcher=0"
        shell: powershell

      - name: Install Python Dependencies
        run: |
          # Install Python dependencies from requirements.txt (if it exists)
          if (Test-Path "requirements.txt") {
            pip install -r requirements.txt
          } else {
            Write-Host "requirements.txt not found."
          }
        shell: powershell

      - name: Run Hello World
        run: python hello.py
        working-directory: ${{ github.workspace }}
        shell: powershell

  release:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Generate Semantic Version and Create Release
        id: semver_and_release
        run: |
          # Custom logic to generate a semantic version
          $major = 1
          $minor = 0
          $patch = (Get-Date -Format "yyMMddHHmmss")
          $semanticVersion = "v$major.$minor.$patch"
          Write-Host "SEMVER_VERSION=$semanticVersion" >> $env:GITHUB_ENV

          # Create GitHub Release
          Write-Host "Creating GitHub Release with tag $semanticVersion"
          Write-Host "Release URL: https://github.com/${env:GITHUB_REPOSITORY}/releases/tag/$semanticVersion"
        shell: powershell

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.SEMVER_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
