name: Self-Hosted Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python 3.11.3
        run: python3 -m venv venv && source venv/bin/activate && pip install python==3.11.3

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Hello World
        run: python hello.py

  release:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Generate Semantic Version
        id: semver
        run: |
          # Custom logic to generate a semantic version
          major=1
          minor=0
          patch=$(date +%y%m%d%H%M%S)
          semanticVersion="v$major.$minor.$patch"
          echo "SEMVER_VERSION=$semanticVersion" >> $GITHUB_ENV

      - name: Debug SEMVER_VERSION
        run: echo "SEMVER_VERSION:${{ env.SEMVER_VERSION }}"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v3
        with:
          tag_name: ${{ env.SEMVER_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Get Release URL
        run: echo "Release URL:https://github.com/${{ github.repository }}/releases/tag/${{ env.SEMVER_VERSION }}"
