name: Self-Hosted Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3' # Replace with your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt # If you have any dependencies

      - name: Run Hello World
        run: python hello.py

  release:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0 # Replace with your desired tag name
          draft: false
          prerelease: false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            retries: 3
            retry-delay: 60000
